spring.application.name=yourpillows
spring.datasource.url=jdbc:mysql://localhost:3306/yourpillow-db
spring.datasource.username=root
spring.datasource.password=Roan1972!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Ensure database tables are updated automatically (for dev)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Flyway if not using migration scripts
spring.flyway.enabled=false

# Enable Actuator Monitoring (Optional)
management.endpoints.web.exposure.include=health, metrics, httptrace
