spring.application.name=yourpillows

# Database-instellingen
spring.datasource.url=jdbc:mysql://localhost:3306/yourpillow-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Roan1972!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate configuratie
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Server settings
server.port=8080

# CORS settings
spring.web.cors.allowed-origins=http://localhost:4173
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Bestanden uploaden
upload.directory=/uploads
spring.resources.static-locations=classpath:/static/,file:/uploads
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Actuator Monitoring (optioneel)
management.endpoints.web.exposure.include=health, metrics
